init:
- ps: if ((Test-Path "${env:ProgramFiles(x86)}\Microsoft Visual Studio\2019\Community") -or (Test-Path "${env:ProgramFiles(x86)}\Microsoft Visual Studio\2019\Preview")) { $env:vs2019 = 'true'; }
- ps: if (Test-Path "$env:ProgramFiles\Microsoft Visual Studio\2022\Community") { $env:vs2022 = 'true'; }
test_script:
- ps: get-path
- where git
- where git-lfs
- where ssh
- where hg
- where svn
- where curl
- where node
- where npm
- where mvn
- where go
- where cmake
- where cpack
- where sqlpackage
- where sqlcmd
- where msbuild
- where vstest.console
- where 7z
- where dotnet
- where erl
- where git-lfs
- where java
- where clang
- where webpicmd
- where choco
- where python
- where pip
- where ruby
- where gem
- where bundle
- where nuget
- where xunit.console
- where chromedriver
- where perl
- where gitversion
- IF ("%vs2019%"=="") && ("%vs2022%"=="") where mspec
- where nunit-console
- where nunit3-console
- npm install gulp -g
- where gulp
- where powershell
- where yarn
- where aws

build: off
