get-path
$whereCommands = @(
"cmd /c where git"
"cmd /c where git-lfs"
"cmd /c where ssh"
"cmd /c where hg"
"cmd /c where svn"
"cmd /c where curl"
"cmd /c where node"
"cmd /c where npm"
"cmd /c where mvn"
"cmd /c where go"
"cmd /c where cmake"
"cmd /c where cpack"
"cmd /c where sqlpackage"
"cmd /c where sqlcmd"
"cmd /c where msbuild"
"cmd /c where vstest.console"
"cmd /c where 7z"
"cmd /c where dotnet"
"cmd /c where dotnetdd"
"cmd /c where erl"
"cmd /c where git-lfs"
"cmd /c where java"
"cmd /c where clang"
"cmd /c where webpicmd"
"cmd /c where choco"
"cmd /c where python"
"cmd /c where pip"
"cmd /c where ruby"
"cmd /c where gem"
"cmd /c where bundle"
"cmd /c where nuget"
"cmd /c where xunit.console"
"cmd /c where chromedriver"
"cmd /c where perl"
"cmd /c where gitversion"
"cmd /c where mspec"
"cmd /c where nunit-console"
"cmd /c where nunit3-console"
"cmd /c npm install gulp -g"
"cmd /c where gulp"
"cmd /c where powershell"
"cmd /c where yarn"
"cmd /c where aws")
foreach ($Command in $whereCommands) {$Command; Invoke-Expression $Command ; if($LastExitCode -ne 0) { $host.SetShouldExit($LastExitCode) }}


